#
# Copyright 2022 Ettus Research, a National Instruments Brand
#
# SPDX-License-Identifier: LGPL-3.0-or-later
#

NATIVE_DMA_INTER_SRCS = $(abspath $(addprefix $(BASE_DIR)/../lib/native_dma_interconnect/, \
native_dma_master.sv \
))
